import { MAX_UPLOAD_BYTES, ALLOWED_IMAGE_TYPES } from "@/lib/upload-constants";

export const MAX_HERO_IMAGE_BYTES = MAX_UPLOAD_BYTES;
export const ALLOWED_HERO_IMAGE_TYPES = ALLOWED_IMAGE_TYPES;
export const HERO_IMAGE_MAX_WIDTH = 1920;
